name: Build (Branches, PRs)

on:
  push:
    branches-ignore:
      "root"

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3

        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Artifacts
        uses: gradle/gradle-build-action@v2

        with:
          arguments: build --stacktrace

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3

        with:
          name: Build and Deploy Artifacts
          path: build/libs/*[0-9].jar
